package lk.ijse.SpiceWholesaleShop.util;

public enum Routes {
    DASHBOARD,CUSTOMER,BILL,CASHIERDASH,EMPLOYEES,ADMINLEASTMOVABLE,LOGIN,ADMINMOSTMOVABLE,ADMINORDERDETAILS,ADMINORDER,ADMINPURCHASE,ADMINREPORT,ADMINPRODUCT,USER,CASHIERCUSTOMER,
    CHASHIEREMPLOYEES,CHASHIERLEASTMOVABLE,CHASHIERMOSTMOVABLE,CHASHIERORDERDETAILS,CHASHIERORDER,CHASHIERPURCHASE,CHASHIERREPORT,CHASHIERPRODUCT,CHASHIERBILL,ADMINPURCHASEDETAILS,
    CASHIERPURCHASEDETAILS
}
